using EPFOptimizerPro.Services.Models;

namespace EPFOptimizerPro.Services;

public static class AdaptiveTaskCatalog
{
    private static readonly IReadOnlyList<AdaptiveTaskDefinition> Definitions =
        new List<AdaptiveTaskDefinition>
        {
            new(
                Name: "Audit",
                Command: "Get-ComputerInfo | Select-Object WindowsProductName, WindowsVersion, OsBuildNumber | Format-List | Out-String",
                TimeoutSeconds: 30,
                AvailableInAudit: true,
                AvailableInOptimize: true,
                Category: AdaptiveTaskCategory.SystemHealth,
                Description: "Collecte les informations principales de Windows.",
                ExecutionKind: AdaptiveTaskExecutionKind.Inventory,
                RiskLevel: AdaptiveTaskRiskLevel.None,
                DurationKind: AdaptiveTaskDurationKind.Short,
                CanManualRerun: false,
                CanAutoRun: false,
                RequiresConfirmation: false,
                RequiresAdministrator: false,
                HaloKind: AdaptiveTaskHaloKind.Specialized,
                ResultParserKey: "audit-system-info",
                RecommendationKey: "system-overview"),
            new(
                Name: "Updates",
                Command: "$session = New-Object -ComObject Microsoft.Update.Session; $searcher = $session.CreateUpdateSearcher(); $result = $searcher.Search('IsInstalled=0 and IsHidden=0'); 'Mises à jour disponibles : ' + $result.Updates.Count",
                TimeoutSeconds: 240,
                AvailableInAudit: true,
                AvailableInOptimize: true,
                Category: AdaptiveTaskCategory.Updates,
                Description: "Recherche les mises à jour Windows disponibles.",
                ExecutionKind: AdaptiveTaskExecutionKind.Diagnostic,
                RiskLevel: AdaptiveTaskRiskLevel.None,
                DurationKind: AdaptiveTaskDurationKind.Medium,
                CanManualRerun: false,
                CanAutoRun: false,
                RequiresConfirmation: false,
                RequiresAdministrator: false,
                HaloKind: AdaptiveTaskHaloKind.Specialized,
                ResultParserKey: "windows-updates-search",
                RecommendationKey: "windows-updates"),
            new(
                Name: "Espace disque système",
                Command: "$drive = Get-CimInstance Win32_LogicalDisk -Filter (\"DeviceID='$env:SystemDrive'\"); if ($null -eq $drive) { throw 'Lecteur système introuvable.' }; $total = [int64]$drive.Size; $free = [int64]$drive.FreeSpace; $percent = if ($total -gt 0) { [math]::Round(($free * 100.0) / $total, 2) } else { 0 }; 'Espace disque système mesuré.'; 'EPF_STRUCTURED_SYSTEM_DISK'; 'Drive=' + $drive.DeviceID; 'TotalBytes=' + $total; 'FreeBytes=' + $free; 'FreePercent=' + $percent.ToString([Globalization.CultureInfo]::InvariantCulture)",
                TimeoutSeconds: 30,
                AvailableInAudit: true,
                AvailableInOptimize: true,
                Category: AdaptiveTaskCategory.SystemHealth,
                Description: "Mesure l'espace disponible sur le lecteur système.",
                ExecutionKind: AdaptiveTaskExecutionKind.Diagnostic,
                RiskLevel: AdaptiveTaskRiskLevel.None,
                DurationKind: AdaptiveTaskDurationKind.Short,
                CanManualRerun: true,
                CanAutoRun: false,
                RequiresConfirmation: true,
                RequiresAdministrator: false,
                HaloKind: AdaptiveTaskHaloKind.Orange,
                ResultParserKey: "system-disk-space",
                RecommendationKey: "storage-cleanup"),            new(
                Name: "Red\u00E9marrage en attente",
                Command: "$cbs = Test-Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Component Based Servicing\\RebootPending'; $wu = Test-Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WindowsUpdate\\Auto Update\\RebootRequired'; $sessionManager = Get-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager' -Name PendingFileRenameOperations -ErrorAction SilentlyContinue; $pendingFiles = $null -ne $sessionManager.PendingFileRenameOperations; $pending = $cbs -or $wu -or $pendingFiles; 'Etat de redemarrage evalue.'; 'EPF_STRUCTURED_PENDING_RESTART'; 'Pending=' + $pending.ToString().ToLowerInvariant(); 'CBS=' + $cbs.ToString().ToLowerInvariant(); 'WindowsUpdate=' + $wu.ToString().ToLowerInvariant(); 'PendingFileRename=' + $pendingFiles.ToString().ToLowerInvariant()",
                TimeoutSeconds: 20,
                AvailableInAudit: true,
                AvailableInOptimize: false,
                Category: AdaptiveTaskCategory.SystemHealth,
                Description: "D\u00E9tecte si Windows attend un red\u00E9marrage.",
                ExecutionKind: AdaptiveTaskExecutionKind.Diagnostic,
                RiskLevel: AdaptiveTaskRiskLevel.None,
                DurationKind: AdaptiveTaskDurationKind.Short,
                CanManualRerun: false,
                CanAutoRun: false,
                RequiresConfirmation: false,
                RequiresAdministrator: false,
                HaloKind: AdaptiveTaskHaloKind.Orange,
                ResultParserKey: "pending-restart",
                RecommendationKey: "windows-restart"),
            new(
                Name: "Temp User",
                Command: "Get-ChildItem -Path $env:TEMP -Force -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue",
                TimeoutSeconds: 90,
                AvailableInAudit: false,
                AvailableInOptimize: true,
                Category: AdaptiveTaskCategory.Maintenance,
                Description: "Nettoie les fichiers temporaires du profil utilisateur.",
                ExecutionKind: AdaptiveTaskExecutionKind.Cleanup,
                RiskLevel: AdaptiveTaskRiskLevel.Low,
                DurationKind: AdaptiveTaskDurationKind.Short,
                CanManualRerun: true,
                CanAutoRun: false,
                RequiresConfirmation: true,
                RequiresAdministrator: false,
                HaloKind: AdaptiveTaskHaloKind.Orange,
                ResultParserKey: "temp-user-cleanup",
                RecommendationKey: "storage-cleanup"),
            new(
                Name: "Temp Win",
                Command: "Get-ChildItem -Path 'C:\\Windows\\Temp' -Force -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue",
                TimeoutSeconds: 90,
                AvailableInAudit: false,
                AvailableInOptimize: true,
                Category: AdaptiveTaskCategory.Maintenance,
                Description: "Nettoie les fichiers temporaires de Windows.",
                ExecutionKind: AdaptiveTaskExecutionKind.Cleanup,
                RiskLevel: AdaptiveTaskRiskLevel.Low,
                DurationKind: AdaptiveTaskDurationKind.Short,
                CanManualRerun: true,
                CanAutoRun: false,
                RequiresConfirmation: true,
                RequiresAdministrator: true,
                HaloKind: AdaptiveTaskHaloKind.Orange,
                ResultParserKey: "temp-windows-cleanup",
                RecommendationKey: "storage-cleanup"),
            new(
                Name: "Corbeille",
                Command: "Clear-RecycleBin -Force -ErrorAction SilentlyContinue",
                TimeoutSeconds: 60,
                AvailableInAudit: false,
                AvailableInOptimize: true,
                Category: AdaptiveTaskCategory.Maintenance,
                Description: "Vide la corbeille Windows.",
                ExecutionKind: AdaptiveTaskExecutionKind.Cleanup,
                RiskLevel: AdaptiveTaskRiskLevel.Low,
                DurationKind: AdaptiveTaskDurationKind.Short,
                CanManualRerun: true,
                CanAutoRun: false,
                RequiresConfirmation: true,
                RequiresAdministrator: false,
                HaloKind: AdaptiveTaskHaloKind.Orange,
                ResultParserKey: "recycle-bin-cleanup",
                RecommendationKey: "storage-cleanup"),
            new(
                Name: "DNS",
                Command: "ipconfig /flushdns",
                TimeoutSeconds: 30,
                AvailableInAudit: false,
                AvailableInOptimize: true,
                Category: AdaptiveTaskCategory.Network,
                Description: "Vide le cache de résolution DNS Windows.",
                ExecutionKind: AdaptiveTaskExecutionKind.Repair,
                RiskLevel: AdaptiveTaskRiskLevel.Low,
                DurationKind: AdaptiveTaskDurationKind.Short,
                CanManualRerun: true,
                CanAutoRun: false,
                RequiresConfirmation: true,
                RequiresAdministrator: true,
                HaloKind: AdaptiveTaskHaloKind.Orange,
                ResultParserKey: "dns-flush",
                RecommendationKey: "network-dns"),
            new(
                Name: "Volumes",
                Command: "Get-Volume | Where-Object DriveLetter | ForEach-Object { Optimize-Volume -DriveLetter $_.DriveLetter }",
                TimeoutSeconds: 600,
                AvailableInAudit: false,
                AvailableInOptimize: true,
                Category: AdaptiveTaskCategory.Maintenance,
                Description: "Optimise les volumes disposant d'une lettre de lecteur.",
                ExecutionKind: AdaptiveTaskExecutionKind.Repair,
                RiskLevel: AdaptiveTaskRiskLevel.Medium,
                DurationKind: AdaptiveTaskDurationKind.Long,
                CanManualRerun: true,
                CanAutoRun: false,
                RequiresConfirmation: true,
                RequiresAdministrator: true,
                HaloKind: AdaptiveTaskHaloKind.Violet,
                ResultParserKey: "volume-optimization",
                RecommendationKey: "storage-optimization"),
            new(
                Name: "SFC",
                Command: "sfc /scannow",
                TimeoutSeconds: 1200,
                AvailableInAudit: false,
                AvailableInOptimize: true,
                Category: AdaptiveTaskCategory.SystemHealth,
                Description: "Vérifie et tente de réparer les fichiers système Windows.",
                ExecutionKind: AdaptiveTaskExecutionKind.Repair,
                RiskLevel: AdaptiveTaskRiskLevel.Medium,
                DurationKind: AdaptiveTaskDurationKind.Long,
                CanManualRerun: true,
                CanAutoRun: false,
                RequiresConfirmation: true,
                RequiresAdministrator: true,
                HaloKind: AdaptiveTaskHaloKind.Violet,
                ResultParserKey: "sfc",
                RecommendationKey: "windows-integrity")
        };

    public static bool TryGetDefinition(
        string taskName,
        out AdaptiveTaskDefinition? definition)
    {
        definition = Definitions.FirstOrDefault(item =>
            item.Name.Equals(taskName, StringComparison.OrdinalIgnoreCase));
        return definition is not null;
    }

    public static IReadOnlyList<AdaptiveTaskDefinition> GetDefinitions(bool optimize)
    {
        return Definitions
            .Where(definition => optimize
                ? definition.AvailableInOptimize
                : definition.AvailableInAudit)
            .ToList();
    }
}